# Site settings
title: DC4420
email: talks@dc4420.org
description: > # this means to ignore newlines until "baseurl:"
  DC4420 - Defcon London

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dc4420.org" # the base hostname & protocol for your site

timezone: Europe/London
permalink:   /:year/:month/:day/

twitter_username: dc4420
facebook_group_id: 282646421860423 
facebook_group_name: DC4420
github: dc4420
# Freenode only
irc: dc4420 
mailing_list: http://lists.dc4420.org/cgi-bin/mailman/listinfo/dc4420

# Build settings
markdown: kramdown
